version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: docker-node-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"